// src/constants/providers.ts
// src/constants/providers.ts

export const PROVIDERS = {
  google: { name: "Google Gemini" },
  gemini: { name: "Gemini (Vertex AI / Gemini API)" },
  openai: { name: "OpenAI (ChatGPT, GPT-4)" },
  anthropic: { name: "Anthropic (Claude)" },
  groq: { name: "Groq" },
  huggingface: { name: "HuggingFace" },
  cohere: { name: "Cohere" },
  cohere_chat: { name: "Cohere Chat" },
  ai21: { name: "AI21" },
  ai21_chat: { name: "AI21 Chat" },
  mistral: { name: "Mistral" },
  codestral: { name: "Codestral" },
  text_completion_codestral: { name: "Text Completion Codestral" },
  moonshot: { name: "Moonshot" },
  deepseek: { name: "DeepSeek" },
  together_ai: { name: "Together AI" },
  openrouter: { name: "OpenRouter" },
  xai: { name: "xAI (Grok)" },
  azure: { name: "Azure OpenAI" },
  azure_ai: { name: "Azure AI" },
  azure_text: { name: "Azure Text" },
  vertex_ai: { name: "Vertex AI" },
  vertex_ai_beta: { name: "Vertex AI (Beta)" },
  replicate: { name: "Replicate" },
  datarobot: { name: "DataRobot" },
  databricks: { name: "Databricks" },
  bedrock: { name: "AWS Bedrock" },
  clarifai: { name: "Clarifai" },
  nvidia_nim: { name: "NVIDIA NIM" },
  sagemaker: { name: "AWS SageMaker" },
  sagemaker_chat: { name: "AWS SageMaker Chat" },
  ollama: { name: "Ollama" },
  ollama_chat: { name: "Ollama Chat" },
  lm_studio: { name: "LM Studio" },
  oobabooga: { name: "Oobabooga" },
  vllm: { name: "VLLM" },
  hosted_vllm: { name: "Hosted VLLM" },
  together: { name: "Together" },
  jina_ai: { name: "Jina AI" },
  deepinfra: { name: "DeepInfra" },
  sambanova: { name: "SambaNova" },
  nlp_cloud: { name: "NLP Cloud" },
  voyage: { name: "Voyage AI" },
  perplexity: { name: "Perplexity" },
  deepgram: { name: "Deepgram (Speech-to-Text)" },
  elevenlabs: { name: "ElevenLabs (Voice)" },
  huggingface_hub: { name: "HuggingFace Hub" },
  fireworks_ai: { name: "Fireworks AI" },
  cohere_text: { name: "Cohere Text" },
  anthropic_text: { name: "Anthropic Text" },
  bytez: { name: "Bytez" },
  ai_ml: { name: "AI-ML" },
  lambda_ai: { name: "Lambda AI" },
  watsonx: { name: "IBM WatsonX" },
  watsonx_text: { name: "WatsonX Text" },
  gradient_ai: { name: "Gradient AI" },
  together_ai_beta: { name: "Together AI (Beta)" },
  topaz: { name: "Topaz" },
  triton: { name: "Triton" },
  compactifai: { name: "CompactifAI" },
  humanloop: { name: "HumanLoop" },
  langfuse: { name: "Langfuse" },
  friendliai: { name: "FriendliAI" },
  featherless_ai: { name: "Featherless AI" },
  ai21_text: { name: "AI21 Text" },
  oci: { name: "Oracle Cloud Infrastructure" },
  cometapi: { name: "CometAPI" },
  wandb: { name: "Weights & Biases (WandB)" },
  hyperbolic: { name: "Hyperbolic" },
  recraft: { name: "Recraft" },
  nscale: { name: "NScale" },
  galadriel: { name: "Galadriel" },
  heroku: { name: "Heroku" },
  ovhcloud: { name: "OVHCloud" },
  vercel_ai_gateway: { name: "Vercel AI Gateway" },
  pg_vector: { name: "Postgres Vector" },
  dotscope: { name: "DotScope" },
  empower: { name: "Empower" },
  predibase: { name: "Predibase" },
  volcengine: { name: "Volcengine" },
  datarobot_ai: { name: "DataRobot AI" },
  baseten: { name: "Baseten" },
  lemonade: { name: "Lemonade" },
  bedrock_ai: { name: "Bedrock AI" },
  aiml: { name: "AIML Platform" },
  custom_openai: { name: "Custom OpenAI" },
  openai_like: { name: "OpenAI-Like" },
  text_completion_openai: { name: "Text Completion OpenAI" },
  github: { name: "GitHub Models" },
  github_copilot: { name: "GitHub Copilot" },
  cloudflare: { name: "Cloudflare AI Gateway" },
  ai21_chat_text: { name: "AI21 Chat + Text" },
  databricks_ai: { name: "Databricks AI" },
  maritalk: { name: "Maritalk" },
  morph: { name: "Morph" },
  ai21_text_chat: { name: "AI21 Text Chat" },
  infinity: { name: "Infinity AI" },
  nebius: { name: "Nebius" },
  litellm_proxy: { name: "LiteLLM Proxy" },
  auto_router: { name: "Auto Router" },
  hosted_vllm_chat: { name: "Hosted VLLM Chat" },
  meta_llama: { name: "Meta Llama" },
  llm_studio: { name: "LLama Studio" },
  v0: { name: "V0 (Vercel)" },
  cloudflare_ai: { name: "Cloudflare AI" },
  dashscope: { name: "Dashscope" },
};
